php-stubs/wordpress-stubs

additionalParams.php, composer.json, functionMap.php, visitor.php
This introduces some more functionality to the node visitor which appends PHPStan-specific `@phpstan-param` and `@phpstan-return` tags to the docblock for given functions and methods.
This allows for us to increase the specificity of return values and parameters for PHPStan usage specifically.
The `functionMap.php` file is formatted in a similar manner to the same file in PHPStan itself. Any number of functions and methods can be added in order to override the return type and zero or more of its parameter types.
The resulting changes for the functions and methods I've added so far can be seen in `wordpress-stubs.php`.
@szepeviktor What do you think?
This relies on https://github.com/php-stubs/generator/pull/13
=> Add additional parameter and return type information to stubs

functionMap.php, visitor.php
Fixes https://github.com/szepeviktor/phpstan-wordpress/issues/63.
This is mainly useful for `wp_slash()` and `wp_unslash()`.
=> Implement generics

source/composer.json
I thought that's the least I could do, since I was kind of annoying in the literal-string issue ;)
but basically nothing changed. not sure how you handle those, feel free  to close if you prefer no update. A new release afterwards would help getting the literal-string fix though I guess hehe
=> Generate stubs for WordPress 6.0.1

functionMap.php
The `$args` parameter for functions related to cron events should be a numerically indexed array. Using an associative array means you might be attempting to use the arguments incorrectly in your cron event callback.
=> Ensure the arguments for cron events are numerically indexed

visitor.php
This adds recursive functionality to the `@type` notation handling, so second- and third- level array shapes are supported.
=> Handle nested `@type` tags

visitor.php
This refactors the code added in #44 so it's more structured. The data about tags and parameters only gets formatted to strings just before it gets output.
When running `./generate.sh` the output to `wordpress-stubs.php` is identical.
This change enables some more processing of parameters that I'd like to do.
=> Tag code refactoring

visitor.php
This PR introduces three improvements:
* Handling for non-static array keys in `@type` tags (fixes #47)
* Handling for array shapes in `@var` tags
* More accurate handling for optional elements in array shapes
=> Support for dynamic keys, `@var`s, and optional elements

visitor.php
=> Expand `$args` array parameters that are described in other functions

visitor.php
This handles functions such as `wp_tag_cloud()` which partially specifies some args and then also inherits its args from `wp_generate_tag_cloud()`.
PHPStan supports duplicate keys in an array shape definition by merging their types if they differ, for example: https://phpstan.org/r/55c06b70-ff98-406d-beca-1d6b32065fe5. This means we can safely merge the two shapes without needing to remove duplicate keys. Neato.
=> Merge arguments when an inheriting function specifies some arguments

generate.sh
These functions are giving notices on php 8+.
The fix is adding a extra php attribute to the methods: #[ReturnTypeWillChange]
There where a couple of difficulties. So I took a different approach.
1. Just using `sed` for a method couldn't target the function of a specific class. So I used php reflection.
2. I wanted to prevent adding multiple `#[ReturnTypeWillChange]` So I check if it's not already present.
So when https://github.com/WordPress/Requests/pull/505 lands, this won't create duplicates.
3. I wanted to make sure the indenting was correct for the attribute.
Overall fun thing to include.
=> Add extra php attribute to methods for 8+ Fixes #52

composer.json, functionMap.php
See https://github.com/szepeviktor/phpstan-wordpress/issues/168 and https://phpstan.org/writing-php-code/narrowing-types#custom-type-checking-functions-and-methods
=> Add `@phpstan-assert` to `is_wp_error`

functionMap.php, functionMap62.php
Adds functions to the map using conditional return types that are currently handled via return type extensions in  [szepeviktor/phpstan-wordpress](https://github.com/szepeviktor/phpstan-wordpress).
Also adds `get_post_types()` (https://github.com/szepeviktor/phpstan-wordpress/pull/177).
Not thoroughly tested yet.
=> Add functions with conditional return types

.gitignore, .travis.yml, composer.json, functionMap.php, functionMap62.php, phpstan.neon, phpunit.xml.dist, tests/TypeInferenceTest.php, tests/data/current_time.php, tests/data/get_comment.php, tests/data/get_object_taxonomies.php, tests/data/get_taxonomies.php, tests/data/has_filter.php, tests/data/mysql2date.php, tests/phpstan.neon
@IanDelMar @szepeviktor @johnbillion 
maybe this is useful to continue with https://github.com/szepeviktor/phpstan-wordpress/pull/182 / https://github.com/szepeviktor/phpstan-wordpress/issues/180?
still missing: phpcs and all the crazy CS rules that Viktor has in the extension repo 😊
=> Add TypeInferenceTest for `current_time()`

functionMap.php, functionMap62.php
@IanDelMar This simplifies these two parameter types so we don't need to maintain the shapes. What do you think?
In #81 I added `See register_post_type() for information on accepted arguments` and `See register_taxonomy() for information on accepted arguments` to the args descriptions in the constructors in WordPress core and then regenerated the stubs, to demonstrate how [the args inheritance](https://github.com/johnbillion/wordpress-stubs/blob/cf154052649f9b35a48fd9590a6a06333eda95fd/visitor.php#L567-L580) works. I can add those to core but we'll need to wait until WordPress 6.3 is released to benefit from them. This PR could be merged in the meantime.
=> Remove the need to maintain these args shapes

functionMap.php, tests/TypeInferenceTest.php, tests/data/is_wp_error.php
I'm not sure what the benefit of `'@phpstan-assert-if-true'=>'\WP_Error $thing'` is, so I left it as is.
=> Add conditional return type for `is_wp_error()`

functionMap.php
1. Removes eight instances of `@phpstan-return` where it's identical to the existing `@return` tag
2. Tighten the allowed types for the `wp_script_is()` status
=> Misc stubs updates

composer.json, visitor.php
Ref: https://github.com/phpstan/phpstan/releases/tag/1.10.12
Not especially useful at the moment, but hey. There are a few other undocumented objects in WordPress core, I'll try to get them documented for 6.3.
=> Add support for object shapes in PHPStan

functionMap.php, tests/TypeInferenceTest.php, tests/data/get_term.php
- Return `array<int|string>` if `$output = 'ARRAY_N'`.
- Return `array<string, int|string>` if default or `$output = 'ARRAY_A'`.
- Return `WP_Term` if default or `$output = 'OBJECT'`.
link https://developer.wordpress.org/reference/functions/get_term/#parameters
=> Add dynamic return type for the get_term function

functionMap.php, tests/TypeInferenceTest.php, tests/data/get_term_by.php
- Return `array<int|string>` if `$output = 'ARRAY_N'`.
- Return `array<string, int|string>` if default or `$output = 'ARRAY_A'`.
- Return `WP_Term` if default or `$output = 'OBJECT'`.
link https://developer.wordpress.org/reference/functions/get_term_by/#parameters
=> Add dynamic return type for the get_term_by function

visitor.php
This PR adds `@phpstan-return never` to functions/methods that will never return a value, and always terminate with a call to `die`/`exit`, `wp_die`, `wp_send_json`, `wp_send_json_success` or `wp_send_json_error`.
There are some functions that are not covered yet. Cases that are not covered are:
- the terminated function call is wrapped in a if-else (e.g. [wp_ajax_send_password_reset()](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-admin/includes/ajax-actions.php#L5582-L5605)),
- a call to `wp_die()` that uses a variable as 3rd argument (e.g. [wp_nonce_ays()](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-includes/functions.php#L3582-L3620)),
- a call to `wp_die()` that explicitly sets the default value for 'exit' (e.g. `wp_die('', '', ['exit' => true])`). …
=> Add @phpstan-return never

visitor.php
Although we leave `Interface_` and `Trait_` nodes at this point
https://github.com/php-stubs/wordpress-stubs/blob/c0a1041ddd384b5224bc8b90e7d1adcc9ef5d11c/visitor.php#L297-L299
we continue traversing to check their methods. Therefore, the parent node of each `ClassMethod` can be either a `Class_`, `Interface_` or `Trait_` node, i.e. a `ClassLike` node.
=> Fix type in variable docblock

functionMap.php
=> Fix typo in parameter name in function map

visitor.php
By
https://github.com/php-stubs/wordpress-stubs/blob/1bb52f7ab7eebe2a72b50f62a16cf68e8b577ed7/visitor.php#L997-L999
we know that `$parts[2]` is set.
=> Remove obsolete isset()

visitor.php
Extends adding never return types to void return types with `return;`.
Logic:
1. Does function/method return anything? If so, the return type can't be never.
2. Does the function method have `return;` statements only? If so, it's a void return type.
3. Logic for never has changed a little. We now look at all expression that are not nested in anything else not only at the last statement + improved check of the 3rd argument for wp_die.
Distinguishing never and void is a little tricky and will take more time.
I'm not sure which branch to use, master or 6.4.0.
=> Use visitor to add `@phpstan-return void`

tests/TypeInferenceTest.php
=> Remove wp_clear_scheduled_hook from TypeInferenceTest

functionMap.php
`get_objects_in_term()` gets added twice. Spotted via tests added in #128.
=> Remove `get_objects_in_term()` from functionMap

visitor.php
https://github.com/php-stubs/wordpress-stubs/pull/110#issuecomment-1801824738
https://github.com/php-stubs/wordpress-stubs/pull/110#issuecomment-1802758520
=> Exclude "must be overriden" from adding return never

finder.php, functionMap.php, phpcs.xml.dist, visitor.php
Avoid Travis result from being polluted by CS errors
=> Fix some cs issues and remove visitor.php from phpcs.xml.dist

visitor.php
@IanDelMar Please review my commits one-by-one.
I have zero clue what I am doing.
The first one: https://github.com/php-stubs/wordpress-stubs/pull/137/commits/8acda8ed6c29b23a1cc6a0669fbd2573276430d5?diff=unified&w=1
Second: https://github.com/php-stubs/wordpress-stubs/pull/137/commits/df08a1eb22c42ed76cff74e6d2c40a98bf396d2e?diff=unified&w=1
3rd: https://github.com/php-stubs/wordpress-stubs/pull/137/commits/afb2a10db1a0de0b911b9fc27805923f9a0ef287?diff=unified&w=1
=> Get rid of complex conditions in visitor.php

phpstan.neon.dist, visitor.php
all the cool guys use this
no, it's just the latest feature toggles enabled basically, https://phpstan.org/config-reference#bleeding-edge
e.g. gives us the list type. and it showed dead code here.
this basically includes https://github.com/php-stubs/wordpress-stubs/pull/106
=> Enable PHPStan listType and alwaysTrueAlwaysReported

functionMap.php, tests/data/wpdb.php
Based on https://github.com/php-stubs/wordpress-stubs/pull/145
Closes https://github.com/php-stubs/wordpress-stubs/issues/143 
I'll do the list in another follow-up, the changes are bigger than I thought and blow the PR up unnecessarily I think
=> Fix wpdb::get_results() return type

functionMap.php, tests/data/get_post_types.php
The result of `get_post_type` is an associative array keyed with the post type slugs.
=> Improve return type for `get_post_types`

source/composer.json
hmm, no difference apparently, not sure what you normally do with this..
thx for the quick merges btw!
=> Generate stubs for WordPress 6.4.3

README.md
Make the build badge green again
=> Replace Travis build badge with GitHub Actions one

functionMap.php
The default type for $callback is ''. Since there are parameters after $callback, we must support the default as well.
Fixes issue #153
=> Fix $callback type for `add_submenu_page`

composer.json
The release of [phpDocumentor/ReflectionDocBlock v5.4.0](https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.4.0) seems to have introduced an issue affecting the visitor functionality. Numerous `@phpstan-param` and `@phpstan-return` annotations are no longer present. Further investigation is needed. Locking the version at 5.3.0 is as a temporary measure until the issue is resolved.
=> Lock phpdocumentor/reflection-docblock version

functionMap.php, source/composer.json
This pull request updates the stubs to WordPress 6.5.
Changes to functionMap.php:
- Removal of `WP_List_Table::display_tablenav` and `WP_List_Table::pagination`. The visitor now adds these PHPStan tags without relying on `functionMap.php`.
- Removal of optional indicators (`?`) for the return type of `WP_Filesystem_*::dirlist()` in accordance with the description in the [documentation](https://developer.wordpress.org/reference/classes/wp_filesystem_base/dirlist/).
Notes:
- `WP_Filesystem_*::dirlist()`: There are now two `@phpstan-return`, one added by the visitor using `@type` and one previously added via `functionMap.php`. There are two issues: the details provided by the new tag are slightly reduced (see `type` key), which should not be problematic from my perspective. Additionally, the …
=> Add stubs for WP 6.5

functionMap.php
The WP_Widget class supports passing an "$instance" array around which contains the value of the current widget settings. 
Without a PHPStan template, adding a type to the $instance array results in warnings like "should be contravariant with parameter" for the following methods:
- form
- update
- widget
Having a template available allows using @extends to pass the array shape around. 
As a bonus, this pull request also includes the full shape of the `$args` passed to `WP_Widget::widget`
=> Support template for WP_Widget settings

source/composer.json, src/Visitor.php, src/WithChildren.php, src/WordPressArg.php
* Generates stubs for WordPress 6.5.3,
* Adds some type declarations,
* Removes dead continue,
* Reduces code nesting
=> Generate stubs for WordPress 6.5.3

phpstan.neon.dist, src/Visitor.php
* (Not related to level 9) Requires `functionMap.php` in the constructor. We hardly gain anything by doing this in `getAdditionalTagsFromMap()`. Adds a doc comment to inform PHPStan of the type change after `array_shift()`.
* Renames `$name` to `$fullSymbolName` to indicate what name the variable holds throughout the method. Adds a doc comment to `$fullSymbolName` to let PHPStan know about its type.
* Replaces a check for the existence of the `stmts` property with checks for `ClassLike` and `Namespace_` entities. This helps PHPStan understand what to expect from `$node->stmts`. Only `ClassLike` and `Namespace_` need their children to be traversed.
=> Raise PHPStan level to 9

functionMap.php
@IanDelMar Would it fix `@phpstan-param @param key-of<T> $offset`?
Discovered in https://github.com/szepeviktor/phpstan-wordpress/issues/219
=> fix WP_REST_Request::offsetExists

composer.json, src/Visitor.php
The [phpdocumentor/reflection-docblock](https://github.com/phpDocumentor/ReflectionDocBlock) was locked to version 5.3.0 in  #165 because version 5.4.0 caused many PHPStan tags to disappear. This was reported in [issue #365](https://github.com/phpDocumentor/ReflectionDocBlock/issues/365) and fixed in version [5.4.1](https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.4.1).
=> Release phpdocumentor/reflection-docblock lock

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_debug_backtrace_summary.php
Function returns `string` by default but may also return `array` of `$pretty` is passed as `false`. 
https://developer.wordpress.org/reference/functions/wp_debug_backtrace_summary/
=> Support dynamic return type for `wp_debug_backtrace_summary`

tests/data/wp_rest_request.php
`WP_REST_Request::get_param()` returns `null` when called with an unknown parameter.
Testing for this results in failed tests.
Related to #186.
cc @lipemat
=> Add/Fix test for unknown parameter in `WP_REST_Request::get_param()`

functionMap.php, src/Visitor.php
This PR assigns discoverable names to properties using the notation `ClassName::$property`. This allows us to use properties in the functionMap and extend the "type inheritance" feature of the visitor to properties.
Input format for the functionMap:
```php
[
'ClassName::$property' => [null, '@phpstan-var' => 'array<string, string>'],
]
```
which will transform
```php
class ClassName {
/**
* @var array
*/
public $property;
}
```
to
```php
class ClassName {
/**
* @var array
* @phpstan-var array<string, string>
*/
public $property;
}
```
=> Assign discoverable names to properties

functionMap.php
Currently, no tests have been added as PHPStan requires bleeding edge to be enabled in order not to discard the type provided via `@param-out`.
Assertions might look like
```php
// tests/data/wp_parse_str.php
declare(strict_types=1);
namespace PhpStubs\WordPress\Core\Tests;
use function wp_parse_str;
use function PHPStan\Testing\assertType;
// The type of `$result` cannot be narrowed further via stubs.
wp_parse_str('key=value');
assertType('array<int|string, array|string>', $result);
wp_parse_str('key1[key2]]=value');
assertType('array<int|string, array|string>', $result);
```
=> Add @param-out for wp_parse_str()

functionMap.php, tests/TypeInferenceTest.php, tests/data/_wp_json_sanity_check.php
I'm not sure if we provide stubs for "private" functions. Since we include them, it might make sense to improve the type accuracy.
=> Add conditional return type for _wp_json_sanity_check()

phpcs.xml.dist
```
<rule ref="NeutronStandard.Functions.TypeHint.UnusedReturnType">
<exclude-pattern>tests/TypeInferenceTest.php</exclude-pattern>
</rule>
```
has been added twice
=> Remove duplicate rule exclusion

functionMap.php, tests/TypeInferenceTest.php, tests/data/absint.php
For constant values other than non-negative integers and arrays, a dynamic return type extension is needed. I.e. for constant positive and negative floats, as well as for constant positive and negative numeric strings.
=> Add cond. return type and param type for absint()

functionMap.php, tests/Faker.php, tests/TypeInferenceTest.php, tests/data/stripslashes.php
This PR also adds a class, `Faker`. This is a helper class for tests to "fake" types. Instead of `$string_ = (string)$_GET['string']`, one can simply use `Faker::type('string')`. This is particularly useful for types that cannot be cast. For example: 
```php
/** @var numeric-string $numericString */
$numericString = $_GET['numericString'];
```
can be simplified to `Faker::type('numeric-string')` as well. @szepeviktor, if you dislike this idea, I’ll revert to the traditional method. Otherwise, I would update all the other tests to use this class. Also, I’m flexible regarding the class name or method names. If there are other preferences, we can rename them.
If we exclude the file from PHPStan analysis, we could even omit the method statements, as the type faking is handled through the …
=> Add dynamic return type for stripslashes_from_strings_only

src/Visitor.php
Improves removal of unused comments by stripping out all comments that do not start with `/**`.
=> Improve removal of unused comments

src/Visitor.php
- Merged `symbolName` logic from `enterNode()` and `getNodeName()` into `getSymbolName()` for improved readability and maintainability.
- Added assertions to detect nodes without names, ensuring issues are caught early.
- Renamed `$fullSymbolName` to `$symbolName` for consistency, as we only handle "full" symbol names.
- Changed the `fullSymbolName` attribute to `WPStubs_symbolName` to minimize the risk of conflicts with existing attributes or potential overrides when extending this visitor, even though such issues are unlikely.
=> Move all symbolName logic into one method

src/Visitor.php
No functional change, just some cleaner code.
=> Remove some funky string juggling for the never/void return type handling

functionMap.php, tests/data/wp_get_archives.php
Returns void even if echo is false
See line [2019 in wp-includes/general-template.php](https://github.com/WordPress/WordPress/blob/70bfe13aa0a9ef7429c226745ca87060ac9c6aca/wp-includes/general-template.php#L2019)
https://github.com/szepeviktor/phpstan-wordpress/pull/243
=> Fix wp_get_archives

functionMap.php
=> Fix parentheses for wp_die

functionMap.php, tests/TypeInferenceTest.php, tests/data/get_user.php, tests/data/get_user_by.php
See [function reference for get_user](https://developer.wordpress.org/reference/functions/get_user/) and [function reference for get_user_by](https://developer.wordpress.org/reference/functions/get_user_by/).
=> Add conditional return type for get_user() and get_user_by()

functionMap.php
https://developer.wordpress.org/reference/functions/get_current_blog_id/
=> Narrow return type for get_current_blog_id

functionMap.php, tests/data/get_term_by.php
`get_term_by` calls `get_terms` and `get_term`, both of which can return a `WP_Error` object if the taxonomy specified in `$args['taxonomy']` (corresponding to the `$taxonomy` parameter of `get_term_by`) does not exist. However, `get_term_by` handles any potential errors from `get_term` and `get_terms` by converting them into a `false` return value, thereby ensuring it never directly returns a `WP_Error` object.
Removing `WP_Error` from the return type of `get_term_by` reflects the actual behaviour of the function.
Closes #284
=> Fix: Remove WP_Error from get_term_by return type

phpstan.neon.dist, tests/Faker.php, tests/data/Faker.php, tests/data/_get_list_table.php, tests/data/get_attachment_taxonomies.php, tests/data/get_object_taxonomies.php, tests/data/get_post_stati.php, tests/data/get_posts.php, tests/data/get_taxonomies_for_attachments.php, tests/data/term_exists.php, tests/data/wp_dropdown_languages.php, tests/data/wpdb.php
This PR uses the `Faker` class for type inference involving constant types in unions and adds several type assertions. While previously not working, constant types in unions can now be used.
=> Use Faker for unions in type inference

functionMap.php
Adding the `phpstan` prefix to the `@template` tag for consistency. We always use the prefixed version. This does not affect functionality, unless a static analyser supports `@template` but not `@phpstan-template`. However, we are not concerned about this, as we use the prefix for all other relevant tags as well.
=> Prefix template tag

functionMap.php, tests/Faker.php, tests/TypeInferenceTest.php, tests/data/Faker.php, tests/data/get_block_wrapper_attributes.php
The function `get_block_wrapper_attributes()` generates a string of HTML attributes from the `key => value` pairs provided in two arrays, one of which is the `$extra_attributes` parameter.
- Attributes in the form `key="value"` are invalid when the key is numeric. Therefore, the type of `$extra_attributes` is narrowed to ensure only attributes with string type names are passed.
- The function only returns an empty string if both attribute arrays are empty. Thus, when `$extra_attributes` is non-empty, the return value is a `non-falsy-string`.
See [WP Dev Resources for get_block_wrapper_attributes()](https://developer.wordpress.org/reference/functions/get_block_wrapper_attributes/)
=> Narrow return type and parameter type for get_block_wrapper_attributes()

functionMap.php, tests/data/wp_unique_id.php
```php
function wp_unique_id( $prefix = '' ) {
static $id_counter = 0;
return $prefix . (string) ++$id_counter;
}
```
See [WP Dev Resources for wp_unique_id()](https://developer.wordpress.org/reference/functions/wp_unique_id/)
- At least the counter is returned, hence non-empty
- The lowest numeric value returned is `'1'`, hence non-falsy.
=> Further narrow return type of wp_unique_id()

functionMap.php, tests/TypeInferenceTest.php, tests/data/get_current_id.php
> `int` The current user’s ID, or 0 if no user is logged in.
See [WP Dev Resources](https://developer.wordpress.org/reference/functions/get_current_user_id/)
=> Narrow return type of get_current_user_id()

functionMap.php, tests/data/wp_unique_id.php
`wp_unique_prefixed_id()` behaves similar to `wp_unique_id()`.
See [WP Dev Resources for wp_unique_id()](https://developer.wordpress.org/reference/functions/wp_unique_prefixed_id/)
- At least the counter is returned, hence non-empty
- The lowest numeric value returned is `'1'`, hence non-falsy.
Cherry picked #308
=> Narrow return type of wp_unique_prefixed_id()

functionMap.php, tests/TypeInferenceTest.php, tests/data/image_link_input_fields.php
The function `image_link_input_fields()` always returns a string containing HTML markup. Therefore, its return type can be narrowed to `non-falsy-string`.
```php
return "
<input type='text' class='text urlfield' name='attachments[$post->ID][url]' value='" . esc_attr( $url ) . "' /><br />
<button type='button' class='button urlnone' data-link-url=''>" . __( 'None' ) . "</button>
<button type='button' class='button urlfile' data-link-url='" . esc_url( $file ) . "'>" . __( 'File URL' ) . "</button>
<button type='button' class='button urlpost' data-link-url='" . esc_url( $link ) . "'>" . __( 'Attachment Post URL' ) . '</button>
";
```
See the [WP Dev Resources](https://developer.wordpress.org/reference/functions/image_link_input_fields/)
=> Narrow return type of image_link_input_fields()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_caption_input_textarea.php
The function `wp_caption_input_textarea()` always returns a string containing HTML markup. Therefore, its return type can be narrowed to `non-falsy-string`.
```php
return '<textarea name="' . $name . '" id="' . $name . '">' . $edit_post->post_excerpt . '</textarea>';
```
See the [WP Dev Resources](https://developer.wordpress.org/reference/functions/wp_caption_input_textarea/)
=> Narrow return type of wp_caption_input_textarea()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_media_insert_url_form.php
The function `wp_media_insert_url_form()` always returns a string containing HTML markup (see [WP Dev Resources](https://developer.wordpress.org/reference/functions/wp_media_insert_url_form/)). Therefore, its return type can be narrowed to `non-falsy-string`.
=> Narrow return type of wp_media_insert_url_form()

functionMap.php, tests/TypeInferenceTest.php, tests/data/get_site_screen_help.php
The function [`get_site_screen_help_sidebar_content()`](https://developer.wordpress.org/reference/functions/get_site_screen_help_sidebar_content/) always returns a string containing HTML markup. Therefore, its return type can be narrowed to `non-falsy-string`.
The function [`get_site_screen_help_tab_args()`](https://developer.wordpress.org/reference/functions/get_site_screen_help_tab_args/) returns a single associative array whose values depend solely on translations. As such, its return type can be narrowed to an array shape.
=> Narrow return type of get_site_screen_help_tab_args() and get_site_screen_help_sidebar_content()

functionMap.php, tests/TypeInferenceTest.php, tests/data/validate_plugin.php
> `int|WP_Error` 0 on success, WP_Error on failure.
See [WP Dev Resources](https://developer.wordpress.org/reference/functions/validate_plugin/)
Accordingly, the return type has been narrowed to `int|WP_Error`. `validate_plugin()` always returns `WP_Error` if `$plugin` is an empty string; therefore, a conditional return has been added.
=> Narrow return type of validate_plugin()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_nav_menu_manage_columns.php
The function [`wp_nav_menu_manage_columns()`](https://developer.wordpress.org/reference/functions/wp_nav_menu_manage_columns/) returns a single associative array whose values depend solely on translations. As such, its return type can be narrowed to an array shape.
=> Narrow return type of wp_nav_menu_manage_columns()

functionMap.php, tests/TypeInferenceTest.php, tests/data/get_available_post_statuses.php
The function [`get_available_post_statuses()`](https://developer.wordpress.org/reference/functions/get_available_post_statuses/) returns the result of `array_keys()`, which is a numerically indexed array. Therefore, its return type can be narrowed to a `list<string>`.
=> Narrow return type of get_available_post_statuses()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_count_terms.php
The function [`wp_count_terms()`](https://developer.wordpress.org/reference/functions/wp_count_terms/) returns
> `string|WP_Error` Numeric string containing the number of terms in that taxonomy or WP_Error if the taxonomy does not exist.
=> Narrow return type of wp_count_terms()

functionMap.php, tests/TypeInferenceTest.php, tests/data/trailingslashit.php
> `string` String with trailing slash added.
See [WP Dev Resources for trailingslashit()](https://developer.wordpress.org/reference/functions/trailingslashit/)
=> Narrow return type of trailingslashit()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_generate_uuid4.php
```php
function wp_generate_uuid4() {
return sprintf(
'%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
mt_rand( 0, 0xffff ),
mt_rand( 0, 0xffff ),
mt_rand( 0, 0xffff ),
mt_rand( 0, 0x0fff ) | 0x4000,
mt_rand( 0, 0x3fff ) | 0x8000,
mt_rand( 0, 0xffff ),
mt_rand( 0, 0xffff ),
mt_rand( 0, 0xffff )
);
}
```
See [WP Dev Resources](https://developer.wordpress.org/reference/functions/wp_generate_uuid4/)
=> Narrow return type of wp_generate_uuid4()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_is_post_revision.php
The function [`wp_is_post_revision()`](https://developer.wordpress.org/reference/functions/wp_is_post_revision/) returns  
> int|false ID of revision’s parent on success, false if not a revision.
- If it's possible for revisions to be orphaned, the parent ID may be `0`; therefore, the return type is narrowed to `int<0, max>` rather than `int<1, max>`.
- For invalid IDs (`<0`), `wp_is_post_revision()` always returns `false`. Accordingly, a conditional return type has been added.
=> Narrow return type of wp_is_post_revision()

functionMap.php, tests/Faker.php, tests/TypeInferenceTest.php, tests/data/Faker.php, tests/data/wp_http_validate_url.php
The function [`wp_http_validate_url()`](https://developer.wordpress.org/reference/functions/wp_http_validate_url/) either returns `false` or the validated `$url`.
- A conditional return type has been added to account for cases where `'' === $url || is_numeric( $url )`, which are considered invalid.
- The use of `@template-phpstan` ensures that `$url` is not generalised to `string`.
=> Narrow return type of wp_http_validate_url()

functionMap.php, tests/data/wp_rand.php
By default, PHPStan considers all functions that return a value to be pure (see [docs on impure functions](https://phpstan.org/writing-php-code/phpdocs-basics#impure-functions)). Therefore, functions that are impure, e.g. [`wp_rand()`](https://developer.wordpress.org/reference/functions/wp_rand/), should be explicitly marked as such.
~~I am not sure how to test this.~~
=> Mark wp_rand as impure

functionMap.php, tests/TypeInferenceTest.php, tests/data/sanitize_title_with_dashes.php
The function [`sanitize_title_with_dashes()`](https://developer.wordpress.org/reference/functions/sanitize_title_with_dashes/) always returns a `lowercase-string` (which may be empty) because of:
```php
if ( seems_utf8( $title ) ) {
if ( function_exists( 'mb_strtolower' ) ) {
$title = mb_strtolower( $title, 'UTF-8' );
}
$title = utf8_uri_encode( $title, 200 );
}
$title = strtolower( $title );
```
The parameter `$context` is documented as:  
> The operation for which the string is sanitized.
> When set to `save`, additional entities are converted to hyphens or stripped entirely. Default `display`.
This aligns with the function’s behaviour: additional entities are converted when `$context === 'save'`, and not converted otherwise (though not only when `$context === 'display'` but for all …
=> Narrow return type and parameter type of sanitize_title_with_dashes()

functionMap.php, phpstan.neon.dist, tests/Faker.php, tests/TypeInferenceTest.php, tests/data/Faker.php, tests/data/get_password_reset_key.php
By default, PHPStan considers all functions that return a value to be pure (see [docs on impure functions](https://phpstan.org/writing-php-code/phpdocs-basics#impure-functions)). Therefore, functions that are impure, e.g. [`get_password_reset_key()`](https://developer.wordpress.org/reference/functions/get_password_reset_key/), should be explicitly marked as such.
~~I am not sure how to test this.~~
=> Mark get_password_reset_key as impure

functionMap.php, tests/data/wp_is_numeric_array.php
I also added more assertions for the `@phpstan-assert-if-true` tag, specifically to verify that types are not generalised. One case of generalisation occurs with constant arrays that have mixed keys. However, in practice this `if` condition will never evaluate to `true`:
```php
$data = [1 => 'intKey', 'key' => 'stringKey'];
if (wp_is_numeric_array($data)) {
// unreachable
}
```
=> Simplify conditional return type of wp_is_numeric_array()

functionMap.php, tests/TypeInferenceTest.php, tests/data/wp_create_nonce.php
The function [`wp_create_nonce()`](https://developer.wordpress.org/reference/functions/wp_create_nonce/) returns a sub-string of `wp_hash()` and therefore returns `lowercase-string&non-falsy-string`.
#331
=> Narrow return type for wp_create_nonce()

functionMap.php, tests/data/wp_error_parameter.php
For `$linkdata['link_name'] = ''` and  `$linkdata['link_url'] = ''` `wp_insert_link()` returns `0` even if `$wp_post = false`. See [lines 196-206 in bookmark.php](https://github.com/WordPress/wordpress-develop/blob/c726220a21d13fdb5409372b652c9460c59ce1db/src/wp-admin/includes/bookmark.php#L196-L206).
=> Fix conditional return type for wp_insert_link()

functionMap.php, tests/TypeInferenceTest.php, tests/data/has_shortcode.php
- If either `$tag` or `$content` is `''` the function `has_shortcode()` always returns `false`.
- If `has_shortcode()` returns `true`, `$content` must be a `non-falsy-string` (it at least contains `[tagName]`) and `$tag` must be a `non-empty-string` (a valid tag name cannot be empty).
=> Add conditional return type and narrow argument type for has_shortcode()

functionMap.php, tests/TypeInferenceTest.php, tests/data/regex.php
[`wp_html_split()`](https://developer.wordpress.org/reference/functions/wp_html_split/) may return `['']` but not `[]` → narrowed from `string[]` to `non-empty-list<string>`.
=> Narrow return type of wp_html_split()

functionMap.php, phpcs.xml.dist, tests/data/param/absint.php, tests/data/pure/absint.php, tests/data/pure/block_version.php, tests/data/pure/bool_from_yn.php
These functions have no side effects and each function’s output depends only on its arguments.
- https://developer.wordpress.org/reference/functions/bool_from_yn/
- https://developer.wordpress.org/reference/functions/absint/
- https://developer.wordpress.org/reference/functions/block_version/
For pure functions, PHPStan reports `Call to function functionName() on a separate line has no effect.` when the function's return value is unused. Therefore, an assignment has been added to the calls in `tests/data/param/absint.php`.
=> Mark bool_from_yn, absint, and block_version as pure

functionMap.php, tests/data/pure/addslashes-gpc.php, tests/data/return/addslashes_gpc.php
See issue #333
Related:
- https://github.com/szepeviktor/phpstan-wordpress/pull/296
- #369
=> Fix return type of addslashes_gpc and mark it as pure

functionMap.php, tests/ParameterTypeTest.php, tests/data/param/register-post-type.php
Narrows the `$post_type` parameter of [`register_post_type()`](https://developer.wordpress.org/reference/functions/register_post_type/#source) as it
> may only contain lowercase alphanumeric characters, dashes, and underscores
and triggers `_doing_it_wrong()` in such cases or if empty.
=> Narrow parameter type for register_post_type

functionMap.php, tests/data/return/sanitize-post.php
See issue #333
Unfortunately, we're losing a lot of type information. However, I think that both [`sanitize_post()`](https://developer.wordpress.org/reference/functions/sanitize_post/) and [`sanitize_post_field()`](https://developer.wordpress.org/reference/functions/sanitize_post_field/) are too complex to be handled via stubs and require return type extensions. `sanitize_post_field()` would also greatly benefit from a rule checking arguments.
=> Fix return type of sanitize_post

functionMap.php, tests/ParameterTypeTest.php, tests/data/param/antispambot.php
Narrows `$hex_encoding` from `int` to `0|1` for [`antispambot()`](https://developer.wordpress.org/reference/functions/antispambot/).
While passing integers other than `0` (default) or `1` does not trigger PHP or WordPress errors, it expands the random range `rand(0, 1 + $hex_encoding)`, allowing values (e.g. `3`) that hit no branch and therefore omit characters. `-1` would preserve correct email addresses, but since the parameter description says:
> Set to 1 to enable hex encoding.
it has been narrowed to `0|1`.
=> Narrow parameter type for antispambot()

tests/data/assert/wp-is-numeric-array.php
An empty array is considered a numeric array. Since PHPStan 2.1.23, this is accounted for, so inside `if (! wp_is_numeric_array($data))` PHPStan correctly infers `$data` as a `non-empty-array`: an empty array would make `wp_is_numeric_array($data)` return `true` and therefore cannot reach the negated branch.
Related:
- https://github.com/phpstan/phpstan/issues/9734
- https://github.com/phpstan/phpstan-src/pull/4225
=> Fix type expectation in ! wp_is_numeric_array() scope
