php-stubs/wordpress-stubs

generate.sh

No literal-string for $query

---

functionMap.php
visitor.php

See https://github.com/szepeviktor/phpstan-wordpress/issues/42
We already have the technology.

`have_posts()` is an impure function

---

functionMap.php
functionMap62.php

Fix conditional return types for get_comment() and get_post()

---

functionMap.php
functionMap62.php

Add get_page_by_path() to function map

---

tests/data/get_taxonomies.php

Fixes a copy-paste mistake in #76

Fix the tests for `get_taxonomies()`

---

functionMap.php
functionMap62.php
tests/TypeInferenceTest.php
tests/data/get_permalink.php

Adds conditional return type for
* `get_permalink()`
* `get_the_permalink()`
* `get_post_permalink`

Add conditional return type for `get_permalink()`

---

functionMap.php

@lipemat I could not resist. I am sorry.
Could you please review this PR?
Fixes #93

Fix dirlist method return type

---

functionMap.php

As per https://github.com/WordPress/wordpress-develop/pull/4407

More tweaking to the `dirlist()` method return type

---

functionMap.php

Hopefully the final adjustment here.
Ref: https://github.com/WordPress/wordpress-develop/pull/4407

The files element can also be false

---

composer.json

Readd symfony/polyfill

---

visitor.php

Related to https://github.com/php-stubs/wordpress-stubs/pull/115#issuecomment-1780030439
With the help of this check I found a typo in a parameter name.

Add check for parameter names in function map

---

visitor.php

Cherry pick #121 onto 6.4

---

visitor.php

* Fixes incorrect handling of wp_dies's return type when 'exit' is not set (https://github.com/php-stubs/wordpress-stubs/pull/122#issuecomment-1783879493).
* Adds check for integer argument.
* Uses `PhpParser\ConstExprEvaluator` to check the 3rd parameter which increases accuracy and readability.

Fix and improve handling of wp_die's 3rd parameter

---

phpcs.xml.dist
phpstan.neon.dist

Check functionMap.php

---

finder.php
phpcs.xml.dist

@IanDelMar Here we go!
All violations must live free!!

Free CS violations!

---

source/composer.json

https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=closed&status=new&status=reopened&status=reviewing&id=!59852&milestone=6.4.1&col=id&col=summary&col=status&col=milestone&col=owner&col=type&col=priority&order=priority

Generate stubs for WordPress 6.4.1

---

functionMap.php

Fix case for WP_Http_Cookie

---

source/composer.json

Greetings to you @szepeviktor 👋

Generate stubs for WordPress 6.4.2

---

.github/workflows/tests.yml

Very simple and based on the travis config.
Feel free to just close this, if you're not interested of course. I didn't try out GitHub Actions before and thought this is a good chance to do so :) Tested over at https://github.com/herndlm/wordpress-stubs/pull/1

Configure GitHub Actions

---

src/WithChildren.php
src/WordPressTag.php

Please someone review this PR.

Fix negative count

---

functionMap.php

As suggested in https://github.com/php-stubs/wordpress-stubs/pull/204#issuecomment-2308991524

Prefix @param-out with phpstan

---

src/Visitor.php

There are numerous comments that, in my opinion, are not utilised by PHPStan or IDEs and therefore only serve to clutter the file. This is primarily in the form of file docblocks and C++-style comments starting with `//`.
I would appreciate it if someone could review these changes to ensure that no valuable information has been removed.

Remove superfluous comments

---

phpcs.xml.dist

See https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/pull/31

Temporarily configure Squiz.WhiteSpace.FunctionSpacing

---

functionMap.php

Narrow return type of did_action()

---

functionMap.php

Fix param type for wp_trigger_error()

---

composer.json

See https://github.com/phpDocumentor/ReflectionDocBlock/issues/408

Add conflict for phpdocumentor/reflection-docblock v5.6.1

---

tests/TypeInferenceTest.php
tests/data/have_posts.php

Asserts the impureness of `have_posts()`

Add test data for have_posts()

---

composer.json

Bump nikic/php-parser

---

tests/data/echo_parameter.php

Add note on void-null conversion

---

phpcs.xml.dist
phpstan.neon.dist
tests/CallToParameterTest.php
tests/Faker.php
tests/IntegrationTest.php
tests/data/Faker.php
tests/data/_get_list_table_params.php
tests/data/absint_params.php
tests/data/add_menu_page_params.php
tests/data/wp_trigger_error_params.php
tests/data/wpdb-params.php

I will add the remaining tests for parameters narrowed in `functionMap.php` gradually.

Start testing narrowing of parameter types
